/**
 * Índice de presentaciones de Análisis y Diseño 2.
 * Para agregar una semana: crea `presentaciones/<slug>/index.html`
 * (puedes copiar la de calidad-de-software/presentaciones/fundamentos-de-calidad
 * como plantilla), añade el PDF en `pdfs/<slug>.pdf` y agrega una entrada aquí
 * con `available: true`. Ejemplo:
 *
 * { week: 1, slug: "introduccion-diseno", title: "Introducción al diseño",
 *   subtitle: "Del análisis al diseño", available: true },
 */
const TOPICS = [
  {
    week: 1,
    slug: "presentacion-del-curso-y-diagnostico",
    title: "Presentación del Curso y Evaluación Diagnóstica",
    subtitle: "Cómo funciona el curso, evaluación, unidades y evaluación diagnóstica",
    available: true,
  },
  {
    week: 1,
    slug: "fundamentos-de-scrum",
    title: "Fundamentos de Scrum",
    subtitle: "Valores ágiles, roles, eventos y artefactos del marco de trabajo Scrum",
    available: true,
  },
  {
    week: 1,
    slug: "historias-de-usuario-tablero-y-backlog",
    title: "Historias de Usuario, Tablero y Backlog",
    subtitle: "Historia de usuario, criterios INVEST, tablero, límites WIP y estimación con story points",
    available: true,
  },
  {
    week: 2,
    slug: "definicion-del-proyecto-de-curso",
    title: "Identificación y Definición del Proyecto",
    subtitle: "Enunciado del problema, interesados, alcance, elevator pitch y roles del equipo",
    available: true,
  },
  {
    week: 2,
    slug: "laboratorio-sprint-0-y-backlog-inicial",
    title: "Laboratorio: Sprint 0 y Backlog Inicial",
    subtitle: "Definición de Terminado y demostración en vivo del montaje del backlog inicial",
    available: true,
  },
  {
    week: 3,
    slug: "modelado-conceptual-y-sus-beneficios",
    title: "Modelado Conceptual: Beneficios en el Desarrollo de Software",
    subtitle: "Qué es un modelo conceptual, sus beneficios y el caso del FBI Virtual Case File",
    available: true,
  },
  {
    week: 3,
    slug: "elaboracion-del-modelo-de-dominio",
    title: "Elaboración del Modelo de Dominio",
    subtitle: "Clases conceptuales, atributos y asociaciones, aplicados al proyecto del curso",
    available: true,
  },
  {
    week: 3,
    slug: "refinamiento-del-modelo-de-dominio",
    title: "Refinamiento del Modelo de Dominio",
    subtitle: "Errores comunes, generalización, paquetes y clases de asociación",
    available: true,
  },
  {
    week: 4,
    slug: "diagrama-de-clases-de-dominio",
    title: "Modelado en UML: Diagrama de Clases de Dominio",
    subtitle: "Notación formal: asociación, agregación, composición, generalización y paquetes",
    available: true,
  },
  {
    week: 4,
    slug: "diagramas-de-secuencia-del-sistema",
    title: "Interfaz Externa del Sistema: Diagramas de Secuencia del Sistema (DSS)",
    subtitle: "El sistema como caja negra, eventos de sistema y su relación con los casos de uso",
    available: true,
  },
  {
    week: 4,
    slug: "laboratorio-de-modelado-de-analisis",
    title: "Laboratorio de Modelado de Análisis",
    subtitle: "Cierre de la Unidad 2: consolidación del modelo de dominio, clases y DSS del proyecto",
    available: true,
  },
  {
    week: 5,
    slug: "introduccion-al-diseno-arquitectural",
    title: "Introducción al Diseño Arquitectural",
    subtitle: "Qué es arquitectura de software, decisiones arquitectónicas, atributos de calidad y la Ley de Conway",
    available: true,
  },
  {
    week: 5,
    slug: "estilos-de-arquitectura",
    title: "Estilos de Arquitectura I y II",
    subtitle: "Monolítica, cliente/servidor, SOA, basada en componentes, concurrente/tiempo real, líneas de producto, orientada a objetos y microservicios",
    available: true,
  },
  {
    week: 6,
    slug: "arquitecturas-n-capas",
    title: "Diseño de Arquitecturas N-Capas",
    subtitle: "El patrón Layers, aislamiento de cambios, capas estrictas vs. relajadas y su mapeo a Controller-Service-Repository",
    available: true,
  },
  {
    week: 6,
    slug: "diagramas-de-despliegue-paquetes-y-componentes",
    title: "Modelado en UML: Diagramas de Despliegue, Paquetes y Componentes",
    subtitle: "Notación formal de paquetes, componentes con interfaces provistas/requeridas y nodos de despliegue",
    available: true,
  },
  {
    week: 6,
    slug: "laboratorio-de-modelado-de-arquitectura",
    title: "Laboratorio de Modelado de Arquitectura",
    subtitle: "Cierre de la Unidad 3: consolidación del estilo arquitectónico, capas y diagramas UML del proyecto",
    available: true,
  },
  {
    week: 7,
    slug: "abstraccion-y-encapsulamiento",
    title: "Abstracción y Encapsulamiento",
    subtitle: "Interfaz vs. detalle interno, ocultamiento de información y por qué el modelo anémico es un antipatrón",
    available: true,
  },
  {
    week: 7,
    slug: "cohesion-y-acoplamiento",
    title: "Cohesión y Acoplamiento",
    subtitle: "Tipos de acoplamiento, señales de baja cohesión (God Object) y el puente hacia GRASP",
    available: true,
  },
  {
    week: 7,
    slug: "herencia-polimorfismo-e-interfaces",
    title: "Herencia, Polimorfismo e Interfaces",
    subtitle: "Cuándo preferir composición sobre herencia, polimorfismo de subtipo e interfaces como contrato",
    available: true,
  },
  {
    week: 8,
    slug: "solid-principio-de-responsabilidad-unica",
    title: "SOLID: Principio de Responsabilidad Única (SRP)",
    subtitle: "Una clase, una razón para cambiar: relación con la cohesión, God Class y refactor guiado por SRP",
    available: true,
  },
  {
    week: 8,
    slug: "solid-ocp-y-lsp",
    title: "SOLID: Open/Closed (OCP) y Liskov Substitution (LSP)",
    subtitle: "Extender sin modificar código probado, sustitución segura de subtipos y el caso Cuadrado-Rectángulo",
    available: true,
  },
  {
    week: 9,
    slug: "solid-isp",
    title: "SOLID: Interface Segregation Principle (ISP)",
    subtitle: "Interfaces gordas, el caso Trabajador/RobotTrabajador, división por rol y relación con SRP y cohesión",
    available: true,
  },
  {
    week: 9,
    slug: "solid-dip-y-laboratorio-solid",
    title: "SOLID: Dependency Inversion (DIP) y Laboratorio de casos de estudio",
    subtitle: "Depender de abstracciones, DIP vs. inyección de dependencias, síntesis de los 5 principios y cierre de la Unidad 4",
    available: true,
  },
  {
    week: 10,
    slug: "grasp-information-expert-y-creator",
    title: "Patrones GRASP: Information Expert, Creator",
    subtitle: "Asignación de responsabilidades: quién tiene la información y quién debe crear el objeto",
    available: true,
  },
  {
    week: 10,
    slug: "grasp-controller-low-coupling-high-cohesion",
    title: "Patrones GRASP: Controller, Low Coupling, High Cohesion",
    subtitle: "El Controller como puerta de entrada del sistema y la formalización de bajo acoplamiento y alta cohesión",
    available: true,
  },
  {
    week: 10,
    slug: "grasp-polymorphism-pure-fabrication-indirection-protected-variations",
    title: "Patrones GRASP: Polymorphism, Pure Fabrication, Indirection, Protected Variations",
    subtitle: "Cierre de los 9 patrones GRASP: variación por tipo, clases artificiales, intermediarios y puntos de variación protegidos",
    available: true,
  },
  {
    week: 11,
    slug: "diagramas-de-secuencia-y-colaboracion-de-diseno",
    title: "Modelado UML Dinámico: Diagramas de Secuencia/Colaboración de Diseño",
    subtitle: "Se abre la caja negra del DSS: objetos, mensajes y el Controller colaborando para cumplir un caso de uso",
    available: true,
  },
  {
    week: 11,
    slug: "diagrama-de-clases-de-diseno",
    title: "Modelado UML Estático: Diagrama de Clases de Diseño",
    subtitle: "Del modelo de dominio al diseño: visibilidad, operaciones, tipos y navegabilidad de las asociaciones",
    available: true,
  },
  {
    week: 11,
    slug: "laboratorio-de-aplicacion-de-patrones-grasp",
    title: "Laboratorio: Aplicación de Patrones GRASP",
    subtitle: "Cada equipo audita su propio diseño contra los 9 patrones GRASP y corrige las violaciones encontradas",
    available: true,
  },
  {
    week: 12,
    slug: "gof-creacionales-i-factory-method-abstract-factory",
    title: "Patrones GoF Creacionales I: Factory Method, Abstract Factory",
    subtitle: "Del catálogo GRASP al catálogo GoF: creación delegada a subclases y familias de productos relacionados",
    available: true,
  },
  {
    week: 12,
    slug: "gof-creacionales-ii-builder-prototype-singleton",
    title: "Patrones GoF Creacionales II: Builder, Prototype, Singleton",
    subtitle: "Construcción paso a paso, clonación de objetos y la controversia del estado global, con laboratorio de implementación",
    available: true,
  },
  {
    week: 13,
    slug: "gof-estructurales-i-adapter-facade-composite",
    title: "Patrones GoF Estructurales I: Adapter, Facade, Composite",
    subtitle: "Segunda familia GoF: compatibilizar interfaces, simplificar subsistemas y componer estructuras parte-todo",
    available: true,
  },
  {
    week: 13,
    slug: "gof-estructurales-ii-decorator-proxy-bridge",
    title: "Patrones GoF Estructurales II: Decorator, Proxy, Bridge",
    subtitle: "Agregar comportamiento en tiempo real, controlar el acceso a un objeto y desacoplar abstracción de implementación, con laboratorio",
    available: true,
  },
  {
    week: 14,
    slug: "gof-comportamiento-i-strategy-observer-command",
    title: "Patrones GoF de Comportamiento I: Strategy, Observer, Command",
    subtitle: "Tercera y última familia GoF: algoritmos intercambiables, notificación uno-a-muchos y acciones encapsuladas como objetos",
    available: true,
  },
  {
    week: 14,
    slug: "gof-comportamiento-ii-state-template-method-iterator",
    title: "Patrones GoF de Comportamiento II: State, Template Method, Iterator",
    subtitle: "Comportamiento dependiente del estado, el esqueleto de un algoritmo y el recorrido uniforme de una colección",
    available: true,
  },
  {
    week: 14,
    slug: "antipatrones-de-diseno-y-laboratorio-de-cierre-unidad-5",
    title: "Antipatrones de Diseño de Software",
    subtitle: "God Object, Spaghetti Code, Golden Hammer, Copy-Paste y Lava Flow, con laboratorio de cierre de la Unidad 5",
    available: true,
  },
  {
    week: 15,
    slug: "concepto-de-deuda-tecnica",
    title: "Concepto de Deuda Técnica",
    subtitle: "Origen del término con Ward Cunningham, el cuadrante de Martin Fowler, causas comunes y cómo se mide y se paga",
    available: true,
  },
  {
    week: 15,
    slug: "codigo-limpio-i-nombres-funciones-comentarios",
    title: "Código Limpio I: Nombres, Funciones, Comentarios",
    subtitle: "Basado en Clean Code de Robert C. Martin: nombres significativos, funciones pequeñas y el verdadero rol de los comentarios",
    available: true,
  },
  {
    week: 15,
    slug: "codigo-limpio-ii-refactorizacion-y-code-smells",
    title: "Código Limpio II: Refactorización y Code Smells",
    subtitle: "Qué es refactorizar, cuándo hacerlo, el catálogo de code smells de Martin Fowler y su relación con los antipatrones de la Unidad 5",
    available: true,
  },
  {
    week: 16,
    slug: "pruebas-unitarias-fundamentos-y-frameworks",
    title: "Pruebas Unitarias de Software: Fundamentos y Frameworks",
    subtitle: "Qué es una prueba unitaria, la pirámide de pruebas, la estructura AAA, las propiedades FIRST y los frameworks por lenguaje",
    available: true,
  },
  {
    week: 16,
    slug: "pruebas-unitarias-tdd-y-buenas-practicas",
    title: "Pruebas Unitarias: TDD y Buenas Prácticas",
    subtitle: "Test-Driven Development de Kent Beck, el ciclo Red-Green-Refactor y la relación entre pruebas y bajo acoplamiento",
    available: true,
  },
  {
    week: 16,
    slug: "laboratorio-pruebas-unitarias-sobre-el-proyecto",
    title: "Laboratorio: Pruebas Unitarias sobre el Proyecto",
    subtitle: "Cierre de la Unidad 6: cada equipo escribe pruebas unitarias reales sobre su propio proyecto de Fábrica Escuela",
    available: true,
  },
  {
    week: 17,
    slug: "cierre-del-curso-sustentacion-y-feedback",
    title: "Cierre del Curso: Sustentación de Proyectos y Feedback",
    subtitle: "Sustentación final de proyectos, síntesis de las 6 unidades del semestre y espacio de feedback del profesor",
    available: true,
  },
];
