/**
 * Índice de presentaciones de Arquitectura de Software.
 * Para agregar una semana: crea `presentaciones/<slug>/index.html`
 * (puedes copiar la de calidad-de-software/presentaciones/fundamentos-de-calidad
 * como plantilla), añade el PDF en `pdfs/<slug>.pdf` y agrega una entrada aquí
 * con `available: true`. Ejemplo:
 *
 * { week: 1, slug: "introduccion-arquitectura", title: "Introducción a la arquitectura",
 *   subtitle: "Qué es y por qué importa", available: true },
 */
const TOPICS = [
  {
    week: 0,
    slug: "presentacion-del-curso",
    title: "Presentación del curso",
    subtitle: "Dinámica semanal, evaluación, unidades y calendario del semestre",
    available: true,
  },
  {
    week: 1,
    slug: "introduccion-backend-frontend-fullstack",
    title: "Introducción a Backend, Frontend y Fullstack",
    subtitle: "Dónde vive el código, con el caso real de HealthCare.gov",
    available: true,
  },
  {
    week: 1,
    slug: "definiciones-arquitectura-software",
    title: "Definiciones de Arquitectura de Software",
    subtitle: "Qué es y qué no es arquitectura, con el caso del monolito de Twitter",
    available: true,
  },
  {
    week: 2,
    slug: "historia-arquitectura-software",
    title: "Historia de la Arquitectura de Software",
    subtitle: "Del IBM System/360 a la nube: cinco eras de la computación",
    available: true,
  },
  {
    week: 2,
    slug: "evolucion-arquitectura-software",
    title: "Evolución de la Arquitectura de Software",
    subtitle: "Tecnologías y frameworks, con el caso real de Ruby on Rails",
    available: true,
  },
  {
    week: 3,
    slug: "diseno-vs-arquitectura",
    title: "Diseño vs Arquitectura",
    subtitle: "Costo de revertir una decisión, con el caso del Aeropuerto de Denver",
    available: true,
  },
  {
    week: 3,
    slug: "uml-vistas-arquitectonicas",
    title: "Integración de UML para Vistas Arquitectónicas",
    subtitle: "El modelo 4+1 de Kruchten y los diagramas del Sprint 1",
    available: true,
  },
  {
    week: 4,
    slug: "rol-arquitecto-software",
    title: "El Rol del Arquitecto de Software",
    subtitle: "Roles, tipos y cualidades, con el caso real de Netflix",
    available: true,
  },
  {
    week: 4,
    slug: "requisitos-no-funcionales-iso25010",
    title: "Requisitos No Funcionales — ISO 25010",
    subtitle: "Por qué son decisiones arquitectónicas, con el caso de Pokémon GO",
    available: true,
  },
  {
    week: 5,
    slug: "conectores-protocolos-garlan-shaw",
    title: "Conectores y Protocolos de Garlan y Shaw",
    subtitle: "Taxonomía de conectores, con el caso real del vuelo 501 de Ariane 5",
    available: true,
  },
  {
    week: 5,
    slug: "stack-tecnologico",
    title: "Stack Tecnológico",
    subtitle: "LAMP, MEAN, MERN y el caso real de Instagram — cierre de la Unidad 1",
    available: true,
  },
  {
    week: 6,
    slug: "posa-tuberias-filtros-blackboard",
    title: "Catálogo POSA: Tuberías y Filtros, Blackboard",
    subtitle: "Dos estilos clásicos para procesar datos: pipelines Unix y sistemas de pizarra",
    available: true,
  },
  {
    week: 6,
    slug: "posa-brokers-mvc",
    title: "Catálogo POSA: Brokers, MVC",
    subtitle: "Cómo se comunican los componentes distribuidos y cómo se organiza la interfaz de usuario",
    available: true,
  },
  {
    week: 7,
    slug: "posa-batch-cliente-servidor",
    title: "Catálogo POSA: Procesamiento por Lotes, Cliente/Servidor (2, 3 y N capas)",
    subtitle: "Del procesamiento nocturno por lotes a las arquitecturas cliente/servidor en capas",
    available: true,
  },
  {
    week: 7,
    slug: "posa-layers-microkernel",
    title: "Catálogo POSA: Layers, Microkernel",
    subtitle: "Organizar el sistema en capas y diseñarlo para que evolucione mediante plugins",
    available: true,
  },
  {
    week: 8,
    slug: "posa-soa-arquitectura-hexagonal",
    title: "Catálogo POSA: SOA, Arquitectura Hexagonal",
    subtitle: "Servicios reutilizables y el corazón de la aplicación protegido de sus dependencias",
    available: true,
  },
  {
    week: 8,
    slug: "posa-microservicios-webhooks",
    title: "Catálogo POSA: Microservicios, WebHooks",
    subtitle: "Servicios pequeños e independientes, y cómo se avisan entre sí sin preguntar",
    available: true,
  },
  {
    week: 9,
    slug: "posa-bff-circuit-breaker-sofea",
    title: "Catálogo POSA: BFF, Circuit Breaker, SOFEA — Cierre del Catálogo",
    subtitle: "Un backend por cliente, protección ante fallos en cascada, y el cliente como orquestador",
    available: true,
  },
  {
    week: 9,
    slug: "estilos-arquitectonicos",
    title: "Estilos Arquitectónicos",
    subtitle: "De los patrones puntuales del catálogo POSA a la vista panorámica de los estilos de sistema",
    available: true,
  },
  {
    week: 10,
    slug: "principios-diseno-software",
    title: "Principios de Diseño de Software (SOLID, DRY, KISS, DIE, YAGNI)",
    subtitle: "Cinco reglas prácticas para que el código no se vuelva insostenible",
    available: true,
  },
  {
    week: 10,
    slug: "arquitecturas-modernas-jamstack-webassembly-websockets",
    title: "Arquitecturas para Aplicaciones Modernas (JAMStack, WebAssembly, WebSockets)",
    subtitle: "Sitios estáticos que parecen dinámicos, código nativo en el navegador, y comunicación en tiempo real",
    available: true,
  },
  {
    week: 11,
    slug: "arquitecturas-modernas-grpc-microfrontends-webrtc-devops",
    title: "Arquitecturas Modernas (gRPC-ProtoBuffer, Microfrontends, WebRTC, Persistencia Políglota) y Ciclo DevOps",
    subtitle: "Comunicación eficiente entre servicios, frontend fragmentado, video en tiempo real, bases de datos especializadas, y el ciclo que las despliega todas",
    available: true,
  },
  {
    week: 11,
    slug: "antipatrones-arquitectura-software",
    title: "Antipatrones de Arquitectura de Software",
    subtitle: "Cuando las decisiones arquitectónicas se convierten en el problema — cierre de la Unidad 2",
    available: true,
  },
  {
    week: 12,
    slug: "desarrollo-basado-en-componentes",
    title: "Desarrollo basado en Componentes",
    subtitle: "Reutilizar software sin pagar el precio en secreto, con el caso real de Heartbleed",
    available: true,
  },
  {
    week: 12,
    slug: "proceso-desarrollo-orientado-arquitectura",
    title: "Proceso de Desarrollo orientado a la Arquitectura",
    subtitle: "Diseñar la estructura antes de que el código la decida por ustedes, con el caso real del Virtual Case File del FBI",
    available: true,
  },
  {
    week: 13,
    slug: "middleware-y-frameworks",
    title: "Middleware y Frameworks — Introducción",
    subtitle: "El software que conecta al software, con el caso real del despacho de ambulancias de Londres",
    available: true,
  },
  {
    week: 13,
    slug: "implementacion-capas-orm",
    title: "Implementación de Capas y Mapeo Objeto-Relacional (ORM)",
    subtitle: "De las capas en el papel al código que las implementa, con el caso real de Stack Overflow — cierre de la Unidad 3",
    available: true,
  },
  {
    week: 14,
    slug: "esquemas-servicios-web-soa",
    title: "Esquemas para el Uso de Servicios Web y Arquitecturas SOA",
    subtitle: "De aplicaciones monolíticas a servicios reutilizables, con el mandato API de Amazon (2002) — apertura de la Unidad 4",
    available: true,
  },
  {
    week: 14,
    slug: "estandares-protocolos-web-services",
    title: "Estándares y Protocolos de Servicios Web (SOAP, WSDL, UDDI, RESTful, HATEOAS, HAL, GraphQL)",
    subtitle: "De los contratos XML rígidos de SOAP al grafo flexible de GraphQL, con el caso real de Facebook (2012)",
    available: true,
  },
  {
    week: 15,
    slug: "web-apis-implementacion-servicios",
    title: "Web APIs e Implementación de Servicios Web",
    subtitle: "Diseñar una API que dure años, con el caso real de Stripe frente a la ruptura de la API de Twitter (2012)",
    available: true,
  },
  {
    week: 15,
    slug: "cloud-native-microservicios-serverless",
    title: "Arquitecturas Cloud Native, Microservicios (DDD, CQRS, Event Sourcing, API Gateway) y Serverless (FaaS)",
    subtitle: "Del monolito de streaming a cientos de microservicios, con el caso real de la migración de Netflix — cierre de la Unidad 4",
    available: true,
  },
  {
    week: 16,
    slug: "principios-arquitectura-software-segura",
    title: "Principios de Arquitectura de Software Segura",
    subtitle: "Cuando la seguridad no es una capa que se agrega al final, con el caso real de Equifax (2017) — apertura de la Unidad 5",
    available: true,
  },
  {
    week: 16,
    slug: "seguridad-en-apis",
    title: "La Importancia de la Seguridad en las APIs",
    subtitle: "La puerta que la mayoría de los ataques modernos usa para entrar, con el caso real de Optus (2022) — cierre de la Unidad 5",
    available: true,
  },
  {
    week: 16,
    slug: "cierre-del-curso",
    title: "Cierre del Curso",
    subtitle: "Agradecimiento y espacio de intervención oral de feedback con los estudiantes",
    available: true,
  },
];
