/**
 * Índice de presentaciones de Técnicas de Programación.
 * Para agregar una semana: crea `presentaciones/<slug>/index.html`
 * (puedes copiar la de calidad-de-software/presentaciones/fundamentos-de-calidad
 * como plantilla), añade el PDF en `pdfs/<slug>.pdf` y agrega una entrada aquí
 * con `available: true`. Ejemplo:
 *
 * { week: 1, slug: "introduccion", title: "Introducción",
 *   subtitle: "Presentación del curso", available: true },
 */
const TOPICS = [
  {
    week: 0,
    slug: "presentacion-del-curso",
    title: "Presentación del curso",
    subtitle: "Unidades, laboratorios y esquema de evaluación",
    available: true,
  },
  {
    week: 1,
    slug: "fundamentos-del-lenguaje-java",
    title: "Fundamentos del Lenguaje Java",
    subtitle: "JDK, JRE, JVM, IDE, convenciones de nombres y primer programa",
    available: true,
  },
  {
    week: 1,
    slug: "paradigma-imperativo-y-operadores",
    title: "Paradigma Imperativo: Sintaxis y Operadores",
    subtitle: "Qué es el paradigma imperativo, y operadores aritméticos y lógicos en Java",
    available: true,
  },
  {
    week: 2,
    slug: "paradigma-imperativo-estructuras-de-control",
    title: "Paradigma Imperativo: Estructuras de Control",
    subtitle: "Condicionales y ciclos for, while, do-while y for-each en Java",
    available: true,
  },
  {
    week: 2,
    slug: "vectores-en-java",
    title: "Vectores en Java",
    subtitle: "Arreglos, matrices, ArrayList y taller grupal de cierre de Unidad 0",
    available: true,
  },
  {
    week: 3,
    slug: "poo-clases-objetos-y-herencia",
    title: "POO: Clases, Objetos y Herencia",
    subtitle: "Atributos, métodos, constructores y reutilización de código con herencia",
    available: true,
  },
  {
    week: 3,
    slug: "poo-sobrecarga-de-metodos",
    title: "POO: Sobrecarga de Métodos",
    subtitle: "Overloading de métodos y constructores, y su diferencia con la sobrescritura",
    available: true,
  },
  {
    week: 4,
    slug: "clases-abstractas-y-static",
    title: "Clases Abstractas y Static",
    subtitle: "Métodos abstractos, atributos y métodos de clase, y constantes static final",
    available: true,
  },
  {
    week: 4,
    slug: "interfaces-y-polimorfismo-1",
    title: "Interfaces y Polimorfismo (Parte 1)",
    subtitle: "Contrato de interfaz, implements múltiple, upcasting y downcasting",
    available: true,
  },
  {
    week: 5,
    slug: "interfaces-y-polimorfismo-2",
    title: "Interfaces y Polimorfismo (Parte 2)",
    subtitle: "Downcasting seguro con instanceof, ArrayList polimórficos y Comparable",
    available: true,
  },
  {
    week: 5,
    slug: "entrada-y-salida-de-informacion",
    title: "Entrada y Salida de Información",
    subtitle: "Scanner, el bug de nextInt()/nextLine() y salida formateada con printf",
    available: true,
  },
  {
    week: 6,
    slug: "del-diagrama-de-clases-a-la-implementacion",
    title: "Del Diagrama de Clases a la Implementación",
    subtitle: "Notación UML, visibilidad, composición, agregación, herencia y multiplicidad",
    available: true,
  },
  {
    week: 6,
    slug: "profundizacion-lambdas-y-streams",
    title: "Profundización: Lambdas y Streams en Java",
    subtitle: "Interfaces funcionales, expresiones lambda y la API de Streams",
    available: true,
  },
  {
    week: 7,
    slug: "principios-solid",
    title: "Principios SOLID",
    subtitle: "Los cinco principios de diseño orientado a objetos, con ejemplos en Java",
    available: true,
  },
  {
    week: 7,
    slug: "codigo-limpio",
    title: "Código Limpio",
    subtitle: "Nombres significativos, funciones pequeñas y comentarios que valen la pena",
    available: true,
  },
  {
    week: 8,
    slug: "github-colaborativo-y-mejores-practicas",
    title: "GitHub Colaborativo y Mejores Prácticas",
    subtitle: "Ramas, commits, Pull Requests y code review para trabajo en equipo",
    available: true,
  },
  {
    week: 8,
    slug: "documentacion-y-optimizacion-de-codigo",
    title: "Documentación y Optimización de Código",
    subtitle: "Javadoc, README, complejidad Big-O y cuándo vale la pena optimizar",
    available: true,
  },
  {
    week: 9,
    slug: "manejo-de-excepciones",
    title: "Manejo de Excepciones en Java",
    subtitle: "try-catch-finally, checked vs unchecked, try-with-resources y excepciones personalizadas",
    available: true,
  },
  {
    week: 9,
    slug: "gestion-de-archivos-texto-y-csv",
    title: "Gestión de Archivos: Texto y CSV",
    subtitle: "Lectura y escritura de archivos con try-with-resources, y estructura de archivos CSV",
    available: true,
  },
  {
    week: 10,
    slug: "gestion-de-archivos-json",
    title: "Gestión de Archivos: JSON",
    subtitle: "Sintaxis JSON y serialización/deserialización de objetos con la librería Gson",
    available: true,
  },
  {
    week: 10,
    slug: "generacion-de-pdf-con-librerias",
    title: "Generación de PDF con Librerías",
    subtitle: "Creación de documentos PDF programáticamente con Apache PDFBox",
    available: true,
  },
  {
    week: 11,
    slug: "junit-y-pruebas-unitarias",
    title: "JUnit y Pruebas Unitarias",
    subtitle: "Automatización de pruebas con JUnit 5: anotaciones, aserciones y buenas prácticas",
    available: true,
  },
  {
    week: 11,
    slug: "analisis-y-visualizacion-de-datos",
    title: "Librerías para Análisis y Visualización de Datos",
    subtitle: "Apache Commons CSV/Math, gráficos con JFreeChart y principios de software inclusivo",
    available: true,
  },
  {
    week: 12,
    slug: "licenciamiento-empaquetado-y-despliegue",
    title: "Licenciamiento, Empaquetado y Despliegue",
    subtitle: "Licencias open source, empaquetado con Maven y despliegue de una librería reutilizable",
    available: true,
  },
  {
    week: 12,
    slug: "reportes-automaticos-con-ia",
    title: "Sistema de Generación Automática de Reportes con IA",
    subtitle: "Arquitectura de un generador de reportes con IA, validación humana y elección responsable de librerías",
    available: true,
  },
];
